---
apiVersion: v1
kind: application
metadata:
  name: devtest.calculator_tcp
  commType: http
spec:
  services:
    - serviceName: calculator_tcp
      components:
        - componentName: calculator_tcp
          imageType: docker
          imageName: calculator_tcp
          httpPort: 10002
          interfaces:
            - interfaceName: context1
              interfaceType: http
              upstreamPath: /time
              visiblity: external
              accessList:
                - app@client
            - interfaceName: calculator_tcp-network
              interfaceType: network
              interfacePort: 10000
              scheme: tcp
              visiblity: external
              accessList:
                - app@client
          resourceProfiles:
            - resourceProfileName: default
              memory: 1024
              cpu: 1
          defaultResourceProfile: default
